version: '3.3'
services:
  pubsubmongo:
    image: mongo:latest
    container_name: "messageinterchangemongo"
    ports:
      - "27017:27017"
  pubsubspringboot:
    image: message-interchange
    container_name: "messageinterchangeboot"
    ports:
      - "8080:8080"
    links:
      - pubsubmongo

